use_frameworks!

platform :ios, '9.0'

target 'VastchainFaceVerify_Example' do
  pod 'VastchainFaceVerify', :path => '../'

  target 'VastchainFaceVerify_Tests' do
    inherit! :search_paths

    
  end
end
